[env:fnk010b]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
board_build.filesystem = littlefs
board_build.partitions = no_ota.csv
board_build.flash_size = 16MB
board_build.psram_type = opi
board_build.memory_type = qio_opi
build_flags =
    -DCORE_DEBUG_LEVEL=0
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
    -DUSER_SETUP_LOADED=1
    -include src/board/tft_setup.h
build_src_filter = +<*> +<buddies/> +<board/>
lib_deps =
    bodmer/TFT_eSPI @ ^2.5.43
    bitbank2/AnimatedGIF @ ^2.1.1
    bblanchon/ArduinoJson @ ^7.0.0
